name: automate
description: "A CLI tool to automate Flutter app deployment to TestFlight, Firebase App Distribution, and Google Play."
version: 1.0.2
repository: https://github.com/abdullahzreqat/automate

environment:
  sdk: ^3.7.2

dependencies:
  args: ^2.7.0

dev_dependencies:
  lints: ^5.1.0

executables:
  deploy: automate
  automate: automate
